"""remove unique constraints from clicks table

Revision ID: 1e8c44224e3a
Revises: 297be52ccf07
Create Date: 2026-06-29 11:46:50.952788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e8c44224e3a'
down_revision: Union[str, Sequence[str], None] = '297be52ccf07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_clicks_short_code'), table_name='clicks')
    op.create_index('idx_clicks_short_code', 'clicks', ['short_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_clicks_short_code', table_name='clicks')
    op.create_index(op.f('idx_clicks_short_code'), 'clicks', ['short_code'], unique=True)
    # ### end Alembic commands ###
